id: P85285275
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Trinle Özer Series
  language: fr
  description: 'Texts by the First Dodrupchen, Jigme Trinle Özer (rdo grub ’jigs med
    phrin las ''od zer, 1745–1821), who was also known as Kunzang Shenpen (kun bzang
    gzhan phan):'
  volume:
    2335e6d5e3bf471bb484ade2e2ec1f0c:
      title: Aspiration at the Moment of Death
      parent: Aspiration Prayers
    bf27bd7d3db941f8a75a7989dc77fb9b:
      title: Brief Dharmapālas Offering
      parent: Dharma Protectors
    aa2213184c89428d8b38394151bc7bfa:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Guru Rinpoche prayers
    20f9da04ecaa486f83429592e4044896:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    111a2631b61c49d79c3f76cbdab7d58a:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    a8e953d0f5d34bcf8c52931716eed4a3:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    3f005131ef6e46a2a6a3e83b9518dcba:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    7871053c438e45f9b03a537d202754e7:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Practices
    f84f9f215c1b45c8b74bbba9ea1a57c3:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Practices
    40fe4d1e49704d549223c8e8e9ec1573:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    b149dfabaad04544927e4db039242dad:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Sādhanas
    e362c48ca25145c9ae512d8d8e7cb655:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-02-28T23:00:39.691725'
last_modified_at: '2022-02-28T23:00:39.691727'
